# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rac.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'rac.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trac.proto\x12\x03rac\"1\n\rDialogRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\"N\n\x0e\x44ialogResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x18\n\x10matched_question\x18\x03 \x01(\t2@\n\nRACService\x12\x32\n\x07Process\x12\x12.rac.DialogRequest\x1a\x13.rac.DialogResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rac_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DIALOGREQUEST']._serialized_start=18
  _globals['_DIALOGREQUEST']._serialized_end=67
  _globals['_DIALOGRESPONSE']._serialized_start=69
  _globals['_DIALOGRESPONSE']._serialized_end=147
  _globals['_RACSERVICE']._serialized_start=149
  _globals['_RACSERVICE']._serialized_end=213
# @@protoc_insertion_point(module_scope)
